### ISSUE TITLE
Google's Physical Web

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/connected-devices-experiments#19]
Let's craft an experiment around Google's physical web.

**Comment by rwood-moz** [comment]
Goal: Build an Eddystone beacon using my Arduino board with a BLE shield, and have it broadcast a Physical Web URL. Verify the beacon and URL are found by Google's open-source Physical Web iOS App.

**Comment by rwood-moz** [comment]
## Project Information

### Name of Project

Google's Physical Web

### Summary

The general idea of the Physical Web is to extend the internet so that one can interact with physical objects around them. Beacons broadcast URLs that are location-sensitive in that the URL will point to a web site that is relevant to the beacon's physical location or purpose. Clients run on mobile phones and scan the area around their current location and discover messages advertised on nearby beacons.

For more details about beacons themselves see my '[Beacons and more Beacons](https://github.com/mozilla/connected-devices-experiments/issues/11)' write-up.

For more information about the Physical Web, refer to [Google's Physical Web Github repo](https://github.com/google/physical-web).

### Project Description

Make an experiment to experience the Physical Web.

### Goals

Build an Eddystone BLE beacon that omits a Physical Web URL, and have it discovered by Google's official open-source Physical Web iOS app. Eddystone beacons can be purchased however they take a few weeks to ship and are expensive for being a tiny piece of hardware. Since I already had an Arduino board I thought I would just try building my own beacon instead.

### Hardware

[Arduino Uno](https://www.arduino.cc/en/Main/ArduinoBoardUno), [RedBear Lab BLE Shield](http://redbearlab.com/bleshield/), 9V battery, iPhone.

### Target Platform

Arduino

### Features

Stand-alone physical web beacon, see [Google's Beacons](https://developers.google.com/beacons/) page.

## Set up

### Arduino Board Setup

Attach the RedBear BLE Shield to the Arduino board, then attach to the computer via the Arduino USB cable.

![img_1178](https://cloud.githubusercontent.com/assets/2198968/13884242/8da92b3e-ed03-11e5-9f83-681e4b644bbb.JPG)
_Arduino Uno with attached RedBear BLE Shield_

### Install Arduino Libraries

To use the RedBear BLE Shield you have to install the corresponding Arduino libraries: "BLE SDK for Arduino" and "RBL_nRF8001". Startup the Arduino SDK and on the menu choose "Sketch" => "Include Library" => "Manage Libraries..." then search for each one. Click on each entry and click "Install".

![physweb2](https://cloud.githubusercontent.com/assets/2198968/13888629/cd3569b0-ed18-11e5-927f-532077f110c5.png)
_Installing libraries in the Arduino SDK_

### Test the BLE Shield

Next I did a quick test of the BLE Shield to ensure it all works fine. With the Arduino still powered up and attached to USB:
- In the Arduino IDE, opened the RedBear controller sketch: File => Examples => RBL_nRF8001 => BLEControllerSketch
- Compiled and uploaded the sketch onto the Arduino via the ‘Upload’ arrow button

![physweb4](https://cloud.githubusercontent.com/assets/2198968/13888754/8b54eef2-ed19-11e5-8b55-e2a2e4aee839.png)
_Uploading the RedBear BLE Controller Sketch_
- Downloaded the RedBearLab BLE Controller iOS app onto my iphone
- Turned my iPhone bluetooth ON
- Started the BLE Controller app, selected ‘BLE Controller’ from the app menu, clicked ‘Scan’.

![img_1186](https://cloud.githubusercontent.com/assets/2198968/13888878/1b511a12-ed1a-11e5-9f39-aebcfe211cfe.PNG)
_BLE Controller App scanning for BLE Shields_
- App found the BLE Shield on my Arduino board, click the BLE Shield entry in the list. Then all of the shield pins are listed, so you know the BLE Shield works

![img_1188](https://cloud.githubusercontent.com/assets/2198968/13888891/2d499316-ed1a-11e5-8b30-70e88f9fd674.PNG)
_BLE Controller App found the BLE Shield and pins are listed_

### Get and Modify the Arduino Sketch

Next I needed the code to actually change the Arduino into an Eddystone BLE beacon. Lucky for me I found this [blog posting](https://www.simplicity.be/article/eddy-and-his-stones-diy-arduino-beacon-mobile-apps) about building an Eddystone beacon from your Arduino board, and that pointed me to this open-source [Arduino sketch in Github](https://github.com/simplicitylab/electronics-experiments/blob/master/Eddy%20and%20his%20stones/arduino.ino).

After grabbing the code all I had to do was change the actual URL that the beacon will broadcast; so I changed it to "www.mozilla.com" so that it would point to installing Firefox. You can find my version of the same sketch here in my [iot-hacking Github repo](https://github.com/rwood-moz/iot-hacking/blob/master/physical-web/arduino-beacon/arduino-beacon.ino).

### Add another Library

The Arduino sketch mentioned above requires an Arduino library called "arduino-BLEPeripheral". So with the sketch open in the Arduino IDE, on the menu I chose "Sketch" => "Include Library" => "Manage Libraries…" then searched for ‘BLEPeripheral’, once it was found I clicked and chose ‘Install".

![physweb-sketch1](https://cloud.githubusercontent.com/assets/2198968/13889623/f7076388-ed1d-11e5-8c2c-c535d59dd6d5.png)
_Installing the BLEPeripheral library in the Arduino IDE_

### Compile and Upload

Next I just had to compile and upload the sketch! Once uploaded the sketch starts to run on the Arduino board automatically.
![physweb-sketch2](https://cloud.githubusercontent.com/assets/2198968/13889655/1c0a4876-ed1e-11e5-8e95-2eb83c8a99d0.png)
_Uploading the beacon sketch_

### Attach Stand-Alone Power

Now that the code is uploaded and running on the Arduino, disconnect it from the USB cable, and attach the 9V battery power supply to the board. Now we have a live stand-alone Eddystone beacon that we can move anywhere!

![img_1194 1](https://cloud.githubusercontent.com/assets/2198968/13888020/4d605b26-ed15-11e5-818c-3f707f623972.JPG)
_Finished Arduino Eddystone BLE Beacon_

### Discover the Beacon on iOS

Next it was time to check if my Physical Web beacon is actually found! I installed the official [Google Physical Web App](https://itunes.apple.com/us/app/physical-web/id927653608?mt=8) on my iPhone, ensured that Bluetooth was turned on, and then started up the app!

As soon as I started the app, it automatically started searching for nearby Eddystone beacons, and my beacon was found. There was only my beacon nearby so it was the only one in the list.

![img_1191](https://cloud.githubusercontent.com/assets/2198968/13889860/1df0c98e-ed1f-11e5-940d-fda4ca421c06.PNG)
_Google's Physical Web app showing my Eddystone beacon_

When I clicked on the beacon entry in the list, it automatically started my phone's browser and navigated to the URL I had coded in the sketch - and presented me with a download button to download the Firefox for iOS App. Success! :)

![img_1192](https://cloud.githubusercontent.com/assets/2198968/13889877/35f651f2-ed1f-11e5-811e-64b43979070f.PNG)
_Result after clicking on my beacon in the Physical Web App beacon list_

## Code Information

### Code Base

The code was already available open-source on Github, so it was fast to grab and modify slightly (only had to change the broadcasted URL). See the source code for my beacon in my [Github iot-hacking repo](https://github.com/rwood-moz/iot-hacking/blob/master/physical-web/arduino-beacon/arduino-beacon.ino).

### How big is the code base (is this really useful)

For my Eddystone beacon it is 28 LOC (not including the supporting Arduino libraries, etc).

For the Physical Web project itself, currently there are 44 contributors on the [Physical Web Github repo](https://github.com/google/physical-web).

For the Eddystone Physical Web beacon protocol itself, at this moment there are 21 contributors on the [Eddystone Github repo](https://github.com/google/eddystone).

### Does it have an interface

The beacon itself has no physical interface; to interact with the beacon Google has an open-source [Android Physical Web app](https://play.google.com/store/apps/details?id=physical_web.org.physicalweb&hl=en) and a [Physical Web iOS app](https://itunes.apple.com/us/app/physical-web/id927653608?mt=8).

### IoT Operating System

Arduino

### Framework

Google's Physical Web

## Protocols

### Wireless Network Protocols

[Bluetooth Low Energy](https://www.bluetooth.com/what-is-bluetooth-technology/bluetooth-technology-basics/low-energy) protocol
[Eddystone beacon](https://github.com/google/eddystone) protocol

## Competitive landscape

### Current Products

There are different types of beacons out there that use different protocols, for example [Apple's iBeacon](https://developer.apple.com/ibeacon/). However the Physical Web project is based on Google's open-source Eddystone beacon protocol. Some beacons are manufactured to support both protocols, some for just one of them. It seems easier to get iBeacons than Eddystone beacons, at least in my limited experience trying to find an Eddystone beacon in Canada.

### Current Usage

I don't know what kind of interest there is in the Physical Web project or how many Eddystone beacons are actually in use today. It looks like Google has a lot of support from several manufacturers to build Eddystone beacons (even though I found it hard to get one here in Canada).

## SWOT

### Strengths

Cool idea to expand the internet to physical objects that exist around our current geographical location.

### Weaknesses

Need a mobile app to interact with the Physical Web.

### Opportunities

If the Physical Web takes off and becomes popular, IMO there is an opportunity for Mozilla to build our own Physical Web interface.

### Threats

Closed-source beacon protocols, hardware, and supporting apps/infrastructure become the most popular and dominate (and silos) this emerging space. Also perhaps this entire concept doesn't gain enough traction.

## Further Notes/ links
- The [Physical Web](https://google.github.io/physical-web/) home page
- [Google Developers: Beacons](https://developers.google.com/beacons/) home page
- Google Developers: [Getting Started with Beacons](https://developers.google.com/beacons/get-started)
-  Google Developers: Beacons [Platform Overview](https://developers.google.com/beacons/overview)
- The Physical Web [github repository](https://github.com/google/physical-web)
- The Physical Web [technical overview](https://github.com/google/physical-web/blob/master/documentation/technical_overview.md)
- The Eddystone protocol [github repository](https://github.com/google/eddystone)
- Google Developers: [Nearby API](https://developers.google.com/nearby/)
- Google Developers: [Proximity Beacon API](https://developers.google.com/beacons/proximity/guides)
- The [Physical Web Cookbook](http://google.github.io/physical-web/cookbook/)
- YouTube: [Introduction to the Physical Web](https://youtu.be/w0XazPrh7r0) (Ubiquity Dev Summit 2016)
- Although perhaps a bit outdated now, a [List of the 9 biggest Beacon Manufacturers](http://www.nodesagency.com/list-9-biggest-beacon-manufacturers/)
- The Physical Web open-source [android app source](https://github.com/google/physical-web/tree/master/android) and the [ios app source](https://github.com/google/physical-web/tree/master/ios)
- The Physical Web [demo app](https://play.google.com/store/apps/details?id=physical_web.org.physicalweb) on the Google Play Store

**Comment by samgiles** [comment]
See also: https://github.com/mozilla-magnet
