### ISSUE TITLE
Johnny-Five

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/connected-devices-experiments#20]
Let's make an experiment around Johnny-Five, the JavaScript IoT framework http://johnny-five.io/.

**Comment by jedireza** [comment]
# Experiment: Johnny Five

| Details |  |
| :-- | --- |
| Summary | Reviewing [`johnny-five`](http://johnny-five.io/); a Node.js framework for robotics. |
| GitHub | https://github.com/rwaldron/johnny-five |
| Competitors | [`cylon.js`](https://cylonjs.com/) |
| Target market | Developers who want to use JS to control robotics. |
| Marketshare / Contributors | 5,700+ stars, 786 forks, 100+ contributors |
| Hardware | Raspberry Pi 2 Model B, Canakit breadboard/LEDs/buttons |
| Target architecture | ARMv7 |
| Demo link | https://github.com/jedireza/j5-experiment |

## Set up

#### Setup time
- ~15-30 minutes installing [`nvm`](https://github.com/creationix/nvm), then
  installing Node 4 LTS
- ~15 minutes to get first LED blinking
- <10 minutes getting second LED blinking after a delay
- <10 minutes getting button to control the LED

#### Setup details

You may need to execute code as a privileged user (`root`); to access to GPIO
or privileged ports (`80`, `443`).

If you want to use `nvm` to manage Node installs, you may have to `$ sudo su`
and install `nvm` for the `root` user too. This is because `nvm` installs Node
inside the user's home directory. 

When running the example code I `$ sudo su`, [`$ nvm use 4`] and then `$ npm
start`.

## Make an LED blink

I started with my RPi, breadboard and LEDs:

![kit](https://cloud.githubusercontent.com/assets/979929/13971131/d903aee8-f04a-11e5-9f4c-aff6d94daaa1.jpg)

Then I found and followed the [`raspi-io`]() example:

![raspi-j5-diagram](https://cloud.githubusercontent.com/assets/979929/13971138/e390e1b4-f04a-11e5-8974-eea20677d8ef.png)

_Source: http://johnny-five.io/examples/raspi-io/_

The code I used for this:

``` js
'use strict'

const Five = require('johnny-five')
const Raspi = require('raspi-io')

const board = Five.Board({
  repl: false,
  io: new Raspi()
})
let led

board.on('ready', function () {
  led = new Five.Led('P1-37')

  led.blink()

  this.on('exit', () => {
    led.off()
  })
})
```

The result:

![led-clip-01](https://cloud.githubusercontent.com/assets/979929/13971141/ee0b0782-f04a-11e5-9e24-1b04ec3213b1.gif)

## Alternately blinking LEDs

Working from there I added another LED and started it with a delay. The code is
now:

``` js
'use strict'

const Five = require('johnny-five')
const Raspi = require('raspi-io')

const board = Five.Board({
  repl: false,
  io: new Raspi()
})
let led
let led2

board.on('ready', function () {
  led = new Five.Led('P1-37')
  led2 = new Five.Led('P1-40')

  led.blink()

  setTimeout(() => {
    led2.blink()
  }, 250)

  this.on('exit', () => {
    led.off()
    led2.off()
  })
})
```

The result:

![led-clip-02](https://cloud.githubusercontent.com/assets/979929/13971147/f6816cbc-f04a-11e5-9d5e-1367433549f0.gif)

## Control LED via button

Next I wanted to control the LED with a button. I used the Arduino diagram from
the button component docs:

![uno-j5-diagram](https://cloud.githubusercontent.com/assets/979929/13971152/0331ff62-f04b-11e5-9e7b-e3685f6afccc.png)

_Source: http://johnny-five.io/api/button/_

The code for this demo:

``` js
'use strict'

const Five = require('johnny-five')
const Raspi = require('raspi-io')

const board = Five.Board({
  repl: false,
  io: new Raspi()
})
let led
let button

board.on('ready', function () {
  led = new Five.Led('P1-37')
  button = new Five.Button('P1-40')

  button.on('press', () => {
    led.toggle()
  })

  this.on('exit', () => {
    led.off()
  })
})
```

The result:

![led-button-01](https://cloud.githubusercontent.com/assets/979929/13971160/0bb8ffa0-f04b-11e5-8de8-b563cff8e185.gif)
